services:
  - type: web
    name: ai-emotion-detection
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements-light.txt && python -c "import nltk; nltk.download('punkt', quiet=True); nltk.download('punkt_tab', quiet=True)"
    startCommand: gunicorn app:app --workers=1 --threads=2 --timeout=120 --bind=0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
    healthCheckPath: /health
