services:
  - type: web
    name: ai-emotion-detection
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --workers=1 --threads=2 --timeout=120 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
    healthCheckPath: /health
    autoDeploy: true
