services:
  - type: web
    name: ai-emotion-detection
    env: python
    buildCommand: pip install -r requirements-light.txt && python -c "import nltk; nltk.download('punkt'); nltk.download('punkt_tab')"
    startCommand: gunicorn --workers=1 --threads=2 --timeout=120 --bind=0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: False
    healthCheckPath: /health
    autoDeploy: true
